occupancy_2d:
  ros__parameters:
    input_topic: /cloud_registered
    output_topic: /slow_occupancy
    fast_output_topic: /fast_occupancy
    dynamic_output_topic: /dynamic_occupancy
    map_frame: camera_init_correct
    base_frame: base_link
    lidar_frame: utlidar_lidar
    min_z_m: -0.25
    max_z_m: 1.4
    resolution_m: 0.1
    width_m: 15.0
    height_m: 15.0
    fast_hit_log_odds_increment: 2.0
    fast_miss_log_odds_decrement: -1.0
    slow_hit_log_odds_increment: 0.5
    slow_miss_log_odds_decrement: -0.1
    dynamic_occupancy_threshold: 18.0
    fast_decay_factor: 0.99
    slow_decay_factor: 0.999
    min_log_odds: -4.0
    max_log_odds: 4.0