occupancy_scan:
  ros__parameters:
    input_topic: /fast_occupancy
    output_topic: /occupancy_scan
    debug_costmap_topic: /occupancy_scan/debug_costmap
    map_frame: camera_init_correct
    base_frame: base_link
    num_rays: 128
    fov_deg: 180.0
    max_range_m: 20.0
    occupancy_threshold: 50
    max_tf_age_sec: 1.0
